services:
  xuitter.db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xuitter
    volumes:
      - mysql.xuitter:/var/lib/mysql
volumes:
    mysql.xuitter: